version: '4'
services:
    web:
        image: nginx:latest
        ports:
            - "8083:80"
            - "7073:443"
        volumes:
            - ./code:/code
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.crt:/etc/nginx/nginx.crt
            - ./nginx.key:/etc/nginx/nginx.key
        links:
            - php
    php:
        build:
            context: .
            dockerfile: Dockerfile_php8
        volumes:
            - ./code:/code
        links:
            - mysql
            - mongo
    mysql:
        image: mysql:8.0.26
        platform: linux/amd64
        ports:
            - '9093:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 111111
        deploy:
            resources:
                limits:
                    memory: 4096M
    mongo:
        image: mongo
        ports:
            - '27018:27017'
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 111111

